# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=200, unique=True)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
